/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Nahda
 */

package com.mycompany.praktikum9;
import javax.swing.JOptionPane;


public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */

    private int updateIndex = -1;

    public TambahDataPanel() {
        initComponents();
    }
    
    private void clearForm(){
        namaTextField.setText("");
        nimTextField.setText("");
        prodiComboBox.setSelectedIndex(0);
        lakiLakiRadioButton.setSelected(false);
        perempuanRadioButton.setSelected(false);
        aktifCheckBox.setSelected(false);
    }

    public void setFormData(Mahasiswa m, int index) {
        namaTextField.setText(m.getNama());
        nimTextField.setText(m.getNim());
        prodiComboBox.setSelectedItem(m.getProdi());
        
        if (m.getJenisKelamin().equals("Laki-Laki")) {
            lakiLakiRadioButton.setSelected(true);
        } else {
            perempuanRadioButton.setSelected(true);
        }
        
        aktifCheckBox.setSelected(m.isActive());
        updateIndex = index;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        prodi = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        lakiLakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        aktifCheckBox = new javax.swing.JCheckBox();
        kirimButton = new javax.swing.JButton();
        prodiComboBox = new javax.swing.JComboBox<>();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Data Mahasiswa");

        nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nama.setText("Nama");

        prodi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prodi.setText("Prodi");

        nim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nim.setText("NIM");

        jenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jenisKelamin.setText("Jenis Kelamin");

        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status.setText("Status");

        lakiLakiRadioButton.setText("Laki Laki");

        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        aktifCheckBox.setText("Aktif");

        kirimButton.setBackground(new java.awt.Color(204, 204, 255));
        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        prodiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro", " " }));
        prodiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodiComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kirimButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lakiLakiRadioButton)
                                .addGap(65, 65, 65)
                                .addComponent(perempuanRadioButton))
                            .addComponent(aktifCheckBox)
                            .addComponent(nimTextField)
                            .addComponent(prodiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nim)
                    .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodi)
                    .addComponent(prodiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisKelamin)
                    .addComponent(lakiLakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status)
                    .addComponent(aktifCheckBox))
                .addGap(18, 18, 18)
                .addComponent(kirimButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String namaInput = namaTextField.getText();
        String nimInput = nimTextField.getText();
        String prodiInput = (String) prodiComboBox.getSelectedItem();
        String jenisKelaminInput = lakiLakiRadioButton.isSelected() ? "Laki-Laki" :
                                   (perempuanRadioButton.isSelected() ? "Perempuan" : "");
        boolean isActiveInput= aktifCheckBox.isSelected();

        // 🔹 1. Cek input kosong
        if (namaInput.isEmpty() || nimInput.isEmpty() || prodiInput.equals("Pilih Prodi")) {
            JOptionPane.showMessageDialog(
                null,
                "Gagal mendapatkan data! Semua kolom harus diisi.",
                "Peringatan",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // 🔹 2. Cek NIM hanya boleh angka
        try {
            Long.parseLong(nimInput);
            if (nimInput.length() != 10){
                JOptionPane.showMessageDialog(
                    null,
                    "NIM harus terdiri dari 10 angka!",
                    "Peringatan",
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                null,
                "NIM harus berupa angka!",
                "Peringatan",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // 🔹 3. Cek jenis kelamin dipilih
        if (!lakiLakiRadioButton.isSelected() && !perempuanRadioButton.isSelected()) {
            JOptionPane.showMessageDialog(
                null,
                "Pilih jenis kelamin terlebih dahulu!",
                "Peringatan",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // 🔹 4. Cek apakah NIM sudah ada di daftar mahasiswa
        if (updateIndex >= 0) {
            // Mode UPDATE
            Mahasiswa m = Mahasiswa.mahasiswa.get(updateIndex);

            // 🔹 Cek jika NIM diubah ke milik orang lain
            for (int i = 0; i < Mahasiswa.mahasiswa.size(); i++) {
                if (i != updateIndex && Mahasiswa.mahasiswa.get(i).getNim().equals(nimInput)) {
                    JOptionPane.showMessageDialog(this,
                        "NIM sudah terdaftar untuk mahasiswa lain!",
                        "Peringatan",
                        JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
            }

            JOptionPane.showMessageDialog(this,
                "Data berhasil diupdate:\n" +
                "Nama : " + namaInput + "\n" +
                "NIM : " + nimInput + "\n" +
                "Prodi : " + prodiInput + "\n" +
                "Jenis Kelamin : " + jenisKelaminInput + "\n" +
                "Status : " + (isActiveInput ? "Aktif" : "Tidak Aktif"),
                "Update Data",
                JOptionPane.INFORMATION_MESSAGE
            );

            updateIndex = -1; // reset ke mode tambah baru
        } else {
            // Mode TAMBAH data baru

            // 🔹 Cek duplikasi NIM
            for (Mahasiswa m : Mahasiswa.mahasiswa) {
                if (m.getNim().equals(nimInput)) {
                    JOptionPane.showMessageDialog(this,
                        "Data dengan NIM " + nimInput + " sudah terdaftar!",
                        "Peringatan",
                        JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
            }

            // 🔹 Tambah data baru
            Mahasiswa mahasiswa = new Mahasiswa(namaInput, nimInput, prodiInput, jenisKelaminInput, isActiveInput);
            Mahasiswa.mahasiswa.add(mahasiswa);

            JOptionPane.showMessageDialog(this,
                "Data berhasil ditambahkan:\n" +
                "Nama : " + namaInput + "\n" +
                "NIM : " + nimInput + "\n" +
                "Prodi : " + prodiInput + "\n" +
                "Jenis Kelamin : " + jenisKelaminInput + "\n" +
                "Status : " + (isActiveInput ? "Aktif" : "Tidak Aktif"),
                "Tambah Data",
                JOptionPane.INFORMATION_MESSAGE
            );
        }

        // 🔹 Bersihkan form setelah selesai
        clearForm();

        // 🔹 Setelah update atau tambah, kembali ke panel Lihat Data
        MainJFrame mainFrame = (MainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        LihatDataPanel lihatPanel = new LihatDataPanel();
        mainFrame.changeMainPanel(lihatPanel);
    }

    private void prodiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodiComboBoxActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jenisKelamin;
    private javax.swing.JButton kirimButton;
    private javax.swing.JRadioButton lakiLakiRadioButton;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JLabel nim;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JLabel prodi;
    private javax.swing.JComboBox<String> prodiComboBox;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
