/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.carrental;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Returns extends javax.swing.JFrame {

    /**
     * Creates new form Returns
     */
    public Returns() {
        initComponents();;
        DisplayRentals(); 
        DisplayReturns(); 
    }
    private void DisplayRentals() {
        try {
            Connection con = DBConnection.connect();
            Statement St = con.createStatement();
            ResultSet Rs = St.executeQuery("SELECT * FROM rental");
            
            // Kode Manual mengisi Tabel (Sama seperti di Rent.java)
            java.sql.ResultSetMetaData rsmd = Rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            java.util.Vector<String> columns = new java.util.Vector<>();
            for (int i = 1; i <= columnCount; i++) {
                columns.add(rsmd.getColumnName(i));
            }
            java.util.Vector<java.util.Vector<Object>> data = new java.util.Vector<>();
            while (Rs.next()) {
                java.util.Vector<Object> row = new java.util.Vector<>();
                for (int i = 1; i <= columnCount; i++) {
                    row.add(Rs.getObject(i));
                }
                data.add(row);
            }
            
            DefaultTableModel model = new DefaultTableModel(data, columns);
            CarsOnRentTb.setModel(model); // Pastikan nama variabel tabel kiri kamu CarsOnRentTb
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void DisplayReturns() {
        try {
            Connection con = DBConnection.connect();
            Statement St = con.createStatement();
            // Sesuaikan nama tabel database kamu, saya asumsikan 'returncar'
            ResultSet Rs = St.executeQuery("SELECT * FROM returncar"); 
            
            java.sql.ResultSetMetaData rsmd = Rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            java.util.Vector<String> columns = new java.util.Vector<>();
            for (int i = 1; i <= columnCount; i++) {
                columns.add(rsmd.getColumnName(i));
            }
            java.util.Vector<java.util.Vector<Object>> data = new java.util.Vector<>();
            while (Rs.next()) {
                java.util.Vector<Object> row = new java.util.Vector<>();
                for (int i = 1; i <= columnCount; i++) {
                    row.add(Rs.getObject(i));
                }
                data.add(row);
            }
            
            DefaultTableModel model = new DefaultTableModel(data, columns);
            ReturnedCarsTb.setModel(model); // Pastikan nama variabel tabel kanan kamu ReturnedCarsTb
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CarsBtn = new javax.swing.JLabel();
        CustBtn = new javax.swing.JLabel();
        RentBTn = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RentIDTb = new javax.swing.JTextField();
        RegNumTb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        DelayTb = new javax.swing.JTextField();
        ReturnBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ReturnDate = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        ReturnedCarsTb = new javax.swing.JTable();
        FeeTb1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CarsOnRentTb = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(140, 169, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 70));

        CarsBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CarsBtn.setForeground(new java.awt.Color(255, 242, 198));
        CarsBtn.setText("Cars");
        CarsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarsBtnMouseClicked(evt);
            }
        });

        CustBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CustBtn.setForeground(new java.awt.Color(255, 242, 198));
        CustBtn.setText("Customers");
        CustBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustBtnMouseClicked(evt);
            }
        });

        RentBTn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        RentBTn.setForeground(new java.awt.Color(255, 242, 198));
        RentBTn.setText("Rent");
        RentBTn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentBTnMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 242, 198));
        jLabel17.setText("Log out");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CustBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CarsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RentBTn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(CarsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RentBTn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(255, 248, 222));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(140, 169, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Rent ID");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(140, 169, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Return Cars");

        RegNumTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNumTbActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(140, 169, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Registration");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(140, 169, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Delay");

        ReturnBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ReturnBtn.setForeground(new java.awt.Color(140, 169, 255));
        ReturnBtn.setText("Return");
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(140, 169, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cars On Rent");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(140, 169, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Return Date");

        ReturnedCarsTb.setBackground(new java.awt.Color(255, 242, 198));
        ReturnedCarsTb.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ReturnedCarsTb.setForeground(new java.awt.Color(50, 50, 50));
        ReturnedCarsTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "RetID", "Registration", "Customer", "Return Date", "Delay", "Fine"
            }
        ));
        ReturnedCarsTb.setGridColor(new java.awt.Color(140, 169, 255));
        ReturnedCarsTb.setRowHeight(25);
        ReturnedCarsTb.setSelectionBackground(new java.awt.Color(140, 169, 255));
        ReturnedCarsTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnedCarsTbMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ReturnedCarsTb);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(140, 169, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Fees");

        CarsOnRentTb.setBackground(new java.awt.Color(255, 242, 198));
        CarsOnRentTb.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        CarsOnRentTb.setForeground(new java.awt.Color(50, 50, 50));
        CarsOnRentTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rent Id", "Registration", "Customer", "Rent Date", "Return Date", "Rent Fee"
            }
        ));
        CarsOnRentTb.setGridColor(new java.awt.Color(140, 169, 255));
        CarsOnRentTb.setRowHeight(25);
        CarsOnRentTb.setSelectionBackground(new java.awt.Color(140, 169, 255));
        CarsOnRentTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarsOnRentTbMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(CarsOnRentTb);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(140, 169, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Returned Cars");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RentIDTb, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegNumTb, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ReturnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DelayTb)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FeeTb1)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 373, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RentIDTb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RegNumTb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DelayTb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FeeTb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegNumTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNumTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegNumTbActionPerformed

    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnActionPerformed
        if(RentIDTb.getText().isEmpty() || RegNumTb.getText().isEmpty() || DelayTb.getText().isEmpty() || FeeTb1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Data belum lengkap!");
        } else {
            try {
                Connection con = DBConnection.connect();
                // Catatan: RetId otomatis (Auto Increment), jadi tidak perlu ditulis
                String sql = "INSERT INTO returncar(Registration, Customer, ReturnDate, Delay, Fine) VALUES(?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                
                pst.setString(1, RegNumTb.getText());
                
                // Mengambil nama customer dari Tabel Sewa yang sedang dipilih
                DefaultTableModel model = (DefaultTableModel)CarsOnRentTb.getModel();
                int MyIndex = CarsOnRentTb.getSelectedRow();
                String CustName = model.getValueAt(MyIndex, 2).toString(); // Asumsi kolom ke-3 adalah Customer Name
                pst.setString(2, CustName);

                java.sql.Date sqlReturnDate = new java.sql.Date(ReturnDate.getDate().getTime());
                pst.setDate(3, sqlReturnDate);
                
                pst.setInt(4, Integer.valueOf(DelayTb.getText()));
                pst.setInt(5, Integer.valueOf(FeeTb1.getText()));
                
                pst.executeUpdate();
                //Update Status
                String updateCarQuery = "UPDATE carregistration SET available='Available' WHERE car_no='" + RegNumTb.getText() + "'";
                Statement st = con.createStatement();
                st.executeUpdate(updateCarQuery);
                //Delete rental yang udah berubah status
                String deleteRentQuery = "DELETE FROM rental WHERE rent_id='" + RentIDTb.getText() + "'";
                Statement st2 = con.createStatement();
                st2.executeUpdate(deleteRentQuery);

                JOptionPane.showMessageDialog(this, "Mobil Berhasil Dikembalikan!");
                
                DisplayRentals();
                DisplayReturns();
                
                Reset();

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_ReturnBtnActionPerformed

    private void ReturnedCarsTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnedCarsTbMouseClicked

    }//GEN-LAST:event_ReturnedCarsTbMouseClicked
    private void Reset(){
        RentIDTb.setText("");
        RegNumTb.setText("");
        DelayTb.setText("");
        FeeTb1.setText("");
    }
    private void CarsOnRentTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarsOnRentTbMouseClicked
        DefaultTableModel model = (DefaultTableModel)CarsOnRentTb.getModel();
        int MyIndex = CarsOnRentTb.getSelectedRow();
        

        RentIDTb.setText(model.getValueAt(MyIndex, 0).toString());
        RegNumTb.setText(model.getValueAt(MyIndex, 1).toString());
        
        // 2. LOGIKA HITUNG DENDA OTOMATIS
        try {
            String dateInString = model.getValueAt(MyIndex, 4).toString(); 
            java.util.Date expectedDate = java.sql.Date.valueOf(dateInString);
            
            java.util.Date actualDate = ReturnDate.getDate();
            
            long diff = actualDate.getTime() - expectedDate.getTime();
            
            long diffDays = java.util.concurrent.TimeUnit.DAYS.convert(diff, java.util.concurrent.TimeUnit.MILLISECONDS);

            if (diffDays > 0) {

                DelayTb.setText(String.valueOf(diffDays));
                

                int fine = (int) diffDays * 1000; //Denda nya
                FeeTb1.setText(String.valueOf(fine));
            } else {
                // Kalo Tepat Waktu atau Lebih Cepat
                DelayTb.setText("0");
                FeeTb1.setText("0");
            }
            DisplayRentals(); 
            DisplayReturns();
            
        } catch (Exception e) {
            e.printStackTrace();
            DelayTb.setText("0");
            FeeTb1.setText("0");
        }
    }//GEN-LAST:event_CarsOnRentTbMouseClicked

    private void CarsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarsBtnMouseClicked
        Cars car = new Cars();
        car.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CarsBtnMouseClicked

    private void CustBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustBtnMouseClicked
        Customers cus = new Customers();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CustBtnMouseClicked

    private void RentBTnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentBTnMouseClicked
        Rent rent = new Rent();
        rent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RentBTnMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Returns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Returns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CarsBtn;
    private javax.swing.JTable CarsOnRentTb;
    private javax.swing.JLabel CustBtn;
    private javax.swing.JTextField DelayTb;
    private javax.swing.JTextField FeeTb1;
    private javax.swing.JTextField RegNumTb;
    private javax.swing.JLabel RentBTn;
    private javax.swing.JTextField RentIDTb;
    private javax.swing.JButton ReturnBtn;
    private com.toedter.calendar.JDateChooser ReturnDate;
    private javax.swing.JTable ReturnedCarsTb;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
