/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.engineer.praktikum9;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class LihatDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form LihatDataPanel
     */
    public LihatDataPanel() {
        initComponents();
        loadData();
    }
    private void loadData(){
        String[] column = {"Nama", "NIM", "Prodi", "Jenis Kelamin", "Status"};
        DefaultTableModel table = new DefaultTableModel(null, column){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        for(Mahasiswa mhs: Mahasiswa.mahasiswas){
            table.addRow(new String[]{ 
                mhs.getNama(), mhs.getNim(), 
                mhs.getProdi(), mhs.getJenisKelamin(), 
                mhs.isActive() ? "Aktif" : "Tidak Aktif" 
            });
        }
        mahasiswaTable.setModel(table);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();
        updButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(234, 246, 246));

        jLabel1.setBackground(new java.awt.Color(34, 40, 49));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lihat Data Mahasiswa");

        mahasiswaTable.setBackground(new java.awt.Color(234, 246, 246));
        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mahasiswaTable);

        updButton.setBackground(new java.awt.Color(0, 173, 181));
        updButton.setText("Update");
        updButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updButtonMouseExited(evt);
            }
        });
        updButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updButtonActionPerformed(evt);
            }
        });

        delButton.setBackground(new java.awt.Color(0, 173, 181));
        delButton.setText("Delete");
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delButtonMouseExited(evt);
            }
        });
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updButton)
                        .addGap(18, 18, 18)
                        .addComponent(delButton)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updButton)
                    .addComponent(delButton))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    private void deleteSelectedRow() {
        int selectedRow = mahasiswaTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dulu!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah kamu yakin ingin menghapus data ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Mahasiswa.mahasiswas.remove(selectedRow);
            loadData();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        }
    }    
    private void updateSelectedRow() {
        int selectedRow = mahasiswaTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!");
            return;
        }

        Mahasiswa mhs = Mahasiswa.mahasiswas.get(selectedRow);


        String newNama = JOptionPane.showInputDialog(this, "Ubah Nama:", mhs.getNama());
        String newNim = JOptionPane.showInputDialog(this, "Ubah Nim:",mhs.getNim());


        if (newNama != null && newNim != null) {
            mhs = new Mahasiswa(newNama, newNim, mhs.getProdi(), mhs.getJenisKelamin(), mhs.isActive());
            Mahasiswa.mahasiswas.set(selectedRow, mhs);
            loadData();
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
        }
    }
    
    private void updButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updButtonActionPerformed
        // TODO add your handling code here:
        updateSelectedRow();
    }//GEN-LAST:event_updButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        deleteSelectedRow();
    }//GEN-LAST:event_delButtonActionPerformed

    private void updButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updButtonMouseEntered
        // TODO add your handling code here:
        updButton.setBackground(new Color(0,140,158));
    }//GEN-LAST:event_updButtonMouseEntered

    private void updButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updButtonMouseExited
        // TODO add your handling code here:
        updButton.setBackground(new Color(0,173,181));
    }//GEN-LAST:event_updButtonMouseExited

    private void delButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMouseEntered
        // TODO add your handling code here:
        delButton.setBackground(new Color(0,140,158));
    }//GEN-LAST:event_delButtonMouseEntered

    private void delButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMouseExited
        // TODO add your handling code here:
        delButton.setBackground(new Color(0,173,181));
    }//GEN-LAST:event_delButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mahasiswaTable;
    private javax.swing.JButton updButton;
    // End of variables declaration//GEN-END:variables
}
