/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.dicoding.praktikum8;

/**
 *
 * @author ASUS
 */
public class KalkulatorFrame extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorFrame
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    public KalkulatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnDigits7 = new javax.swing.JButton();
        jBtnDigits8 = new javax.swing.JButton();
        jBtnDigits9 = new javax.swing.JButton();
        jBtnDigits4 = new javax.swing.JButton();
        jBtnDigits5 = new javax.swing.JButton();
        jBtnDigits6 = new javax.swing.JButton();
        jBtnDigits1 = new javax.swing.JButton();
        jBtnDigits2 = new javax.swing.JButton();
        jBtnDigits3 = new javax.swing.JButton();
        jBtnTimes = new javax.swing.JButton();
        jBtnMinus = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnResult = new javax.swing.JButton();
        jBtnDigits0 = new javax.swing.JButton();
        jBtnComa = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnDel = new javax.swing.JButton();
        jBtnCE = new javax.swing.JButton();
        jBtnDivide = new javax.swing.JButton();
        jTxtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnDigits7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits7.setText("7");
        jBtnDigits7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 33));

        jBtnDigits8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits8.setText("8");
        jBtnDigits8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, 33));

        jBtnDigits9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits9.setText("9");
        jBtnDigits9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 50, 33));

        jBtnDigits4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits4.setText("4");
        jBtnDigits4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, 35));

        jBtnDigits5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits5.setText("5");
        jBtnDigits5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 50, 35));

        jBtnDigits6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits6.setText("6");
        jBtnDigits6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 50, 35));

        jBtnDigits1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits1.setText("1");
        jBtnDigits1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 33));

        jBtnDigits2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits2.setText("2");
        jBtnDigits2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 50, 33));

        jBtnDigits3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits3.setText("3");
        jBtnDigits3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 50, 33));

        jBtnTimes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnTimes.setText("x");
        jBtnTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTimesActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 50, 33));

        jBtnMinus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnMinus.setText("-");
        jBtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 50, 35));

        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 50, 33));

        jBtnResult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnResult.setText("=");
        jBtnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResultActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 50, 33));

        jBtnDigits0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDigits0.setText("0");
        jBtnDigits0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDigits0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDigits0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 33));

        jBtnComa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnComa.setText(".");
        jBtnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComaActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnComa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 50, 33));

        jBtnC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 50, 33));

        jBtnDel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDel.setText("<");
        jBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDelActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 33));

        jBtnCE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCE.setText("CE");
        getContentPane().add(jBtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 50, 33));

        jBtnDivide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDivide.setText(":");
        jBtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 50, 33));

        jTxtResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtResult.setText(" ");
        jTxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtResultActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void EnterNumbers(String q){
        String nums = jTxtResult.getText() + q;
        jTxtResult.setText(nums);
    }
    
    private void jBtnTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTimesActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jTxtResult.getText());
        jTxtResult.setText("");
        op = "*";
    }//GEN-LAST:event_jBtnTimesActionPerformed

    private void jBtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivideActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jTxtResult.getText());
        jTxtResult.setText("");
        op = "/";
    }//GEN-LAST:event_jBtnDivideActionPerformed

    private void jTxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtResultActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxtResultActionPerformed

    private void jBtnDigits7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits7ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("7");
    }//GEN-LAST:event_jBtnDigits7ActionPerformed

    private void jBtnDigits8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits8ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("8");
    }//GEN-LAST:event_jBtnDigits8ActionPerformed

    private void jBtnDigits9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits9ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("9");
    }//GEN-LAST:event_jBtnDigits9ActionPerformed

    private void jBtnDigits4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits4ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("4");
    }//GEN-LAST:event_jBtnDigits4ActionPerformed

    private void jBtnDigits5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits5ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("5");
    }//GEN-LAST:event_jBtnDigits5ActionPerformed

    private void jBtnDigits6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits6ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("6");
    }//GEN-LAST:event_jBtnDigits6ActionPerformed

    private void jBtnDigits1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits1ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("1");
    }//GEN-LAST:event_jBtnDigits1ActionPerformed

    private void jBtnDigits2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits2ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("2");
    }//GEN-LAST:event_jBtnDigits2ActionPerformed

    private void jBtnDigits3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits3ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("3");
    }//GEN-LAST:event_jBtnDigits3ActionPerformed

    private void jBtnDigits0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDigits0ActionPerformed
        // TODO add your handling code here:
        EnterNumbers("0");
    }//GEN-LAST:event_jBtnDigits0ActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        // TODO add your handling code here:
        jTxtResult.setText("");
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinusActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jTxtResult.getText());
        jTxtResult.setText("");
        op = "-";
    }//GEN-LAST:event_jBtnMinusActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jTxtResult.getText());
        jTxtResult.setText("");
        op = "+";
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDelActionPerformed
        // TODO add your handling code here:
        String backSp = null;
        if(jTxtResult.getText().length() > 0){
            StringBuilder sb = new StringBuilder(jTxtResult.getText());
            sb.deleteCharAt(jTxtResult.getText().length() - 1);
            backSp = sb.toString();
            jTxtResult.setText(backSp);
        }
    }//GEN-LAST:event_jBtnDelActionPerformed

    private void jBtnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComaActionPerformed
        // TODO add your handling code here:
        if(! jTxtResult.getText().contains(".")){
            jTxtResult.setText(jTxtResult.getText() + jBtnComa.getText());
        }
    }//GEN-LAST:event_jBtnComaActionPerformed

    private void jBtnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResultActionPerformed
        // TODO add your handling code here:
        NumEnter2 = Double.parseDouble(jTxtResult.getText());
        if(op == "+"){
            Result = NumEnter1 + NumEnter2;
            jTxtResult.setText(String.valueOf(Result));
        }else if(op == "-"){
            Result = NumEnter1 - NumEnter2;
            jTxtResult.setText(String.valueOf(Result));
        }
        else if(op == "*"){
            Result = NumEnter1 * NumEnter2;
            jTxtResult.setText(String.valueOf(Result));
        }else if(op == "/"){
            Result = NumEnter1 / NumEnter2;
            jTxtResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_jBtnResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnCE;
    private javax.swing.JButton jBtnComa;
    private javax.swing.JButton jBtnDel;
    private javax.swing.JButton jBtnDigits0;
    private javax.swing.JButton jBtnDigits1;
    private javax.swing.JButton jBtnDigits2;
    private javax.swing.JButton jBtnDigits3;
    private javax.swing.JButton jBtnDigits4;
    private javax.swing.JButton jBtnDigits5;
    private javax.swing.JButton jBtnDigits6;
    private javax.swing.JButton jBtnDigits7;
    private javax.swing.JButton jBtnDigits8;
    private javax.swing.JButton jBtnDigits9;
    private javax.swing.JButton jBtnDivide;
    private javax.swing.JButton jBtnMinus;
    private javax.swing.JButton jBtnResult;
    private javax.swing.JButton jBtnTimes;
    private javax.swing.JTextField jTxtResult;
    // End of variables declaration//GEN-END:variables
}
